package com.submate.app.webguide.state;

public enum PageState {
    LOGIN,
    MEMBERSHIP_JOIN,
    MEMBERSHIP,
    CANCELLATION_HELP,
    MY_MEMBERSHIP,
    MEMBERSHIP_SETTINGS,
    MEMBERSHIP_MANAGEMENT,
    CANCELLATION_ENTRY,
    RECURRING_CANCEL_CONFIRM,
    FINAL_CANCEL_CONFIRM,
    CANCEL_COMPLETE,
    OTHER_NAVER_PAGE,
    UNSUPPORTED_PAGE
}
